name: CI
on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  benchmark:
    name: Run julia benchmark
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: runner.os−test−env.cache−name−{{ hashFiles('**/Project.toml') }}
          restore-keys: |
            runner.os−test−
            ${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Run benchmark
        run: |
          julia  -e 'import Pkg; Pkg.add("LaplaceRedux")'
          julia  -e 'import Pkg; Pkg.add("Flux")'
          julia  -e 'import Pkg; Pkg.add("Plots")'
          julia  -e 'import Pkg; Pkg.add("OneHotArrays")'
          julia  -e 'import Pkg; Pkg.add("MLUtils")'
          julia  -e 'import Pkg; Pkg.add("FLoops")'
          julia  -e 'import Pkg; Pkg.add("StatsBase")'
          julia  -e 'import Pkg; Pkg.add("SortingAlgorithms")'
          julia  -e 'import Pkg; Pkg.add("MLStyle")'
          cd test/benchmarks
          julia --project --color=yes -e '
            using Pkg;
            Pkg.instantiate();
            include("BenchmarkUnbatchedFit.jl")'

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1.17.0
        with:
          name: Julia benchmark result
          tool: 'julia'
          output-file-path: test/benchmarks/output.json
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
          github-token: ${{ secrets.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 }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '125%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@Andrei32Ionescu'